'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ReportStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WakeOnLan.ReportStrings", GetType(ReportStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Broadcast 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepBroadcast() As String
            Get
                Return ResourceManager.GetString("RepBroadcast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Emergency shutdown? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepEmergency() As String
            Get
                Return ResourceManager.GetString("RepEmergency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Group 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepGroup() As String
            Get
                Return ResourceManager.GetString("RepGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IP Address 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepIP() As String
            Get
                Return ResourceManager.GetString("RepIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 MAC Address 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepMAC() As String
            Get
                Return ResourceManager.GetString("RepMAC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Name 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepName() As String
            Get
                Return ResourceManager.GetString("RepName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Netbios name 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepNetbios() As String
            Get
                Return ResourceManager.GetString("RepNetbios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown command line 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RepShutdown() As String
            Get
                Return ResourceManager.GetString("RepShutdown", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
