'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class OptionProperties
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WakeOnLan.OptionProperties", GetType(OptionProperties).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Version 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AppVersion() As String
            Get
                Return ResourceManager.GetString("AppVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Application version 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AppVersionDescription() As String
            Get
                Return ResourceManager.GetString("AppVersionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Automatically check for updates 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AutoCheck() As String
            Get
                Return ResourceManager.GetString("AutoCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Broadcast Address 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Broadcast_Address() As String
            Get
                Return ResourceManager.GetString("Broadcast_Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enter the broadcast IP Address for the WOL broadcast packets. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Broadcast_AddressDescription() As String
            Get
                Return ResourceManager.GetString("Broadcast_AddressDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Application 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property cat_Application() As String
            Get
                Return ResourceManager.GetString("cat_Application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Emergency settings 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property cat_Emergency() As String
            Get
                Return ResourceManager.GetString("cat_Emergency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property cat_Shutdown() As String
            Get
                Return ResourceManager.GetString("cat_Shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 WOL 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property cat_WOL() As String
            Get
                Return ResourceManager.GetString("cat_WOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Database path 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property dbPath() As String
            Get
                Return ResourceManager.GetString("dbPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Time delay 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Delay() As String
            Get
                Return ResourceManager.GetString("Delay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The default time delay for shutdowns. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DelayDescription() As String
            Get
                Return ResourceManager.GetString("DelayDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Time delay 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property EmergencyDelay() As String
            Get
                Return ResourceManager.GetString("EmergencyDelay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The time delay for emergency shutdowns. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property EmergencyDelayDescription() As String
            Get
                Return ResourceManager.GetString("EmergencyDelayDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Default Message 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property EmergencyShutdown() As String
            Get
                Return ResourceManager.GetString("EmergencyShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The emergency shutdown message. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property EmergencyShutdownDescription() As String
            Get
                Return ResourceManager.GetString("EmergencyShutdownDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable sound 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Enable_Sound() As String
            Get
                Return ResourceManager.GetString("Enable_Sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Play a sound when a monitored server comes online, or stops responding. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Enable_SoundDescription() As String
            Get
                Return ResourceManager.GetString("Enable_SoundDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Force shutdown 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Force() As String
            Get
                Return ResourceManager.GetString("Force", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Force remote server to shutdown.  Unsaved files will be lost. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ForceDescription() As String
            Get
                Return ResourceManager.GetString("ForceDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reboot 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Reboot() As String
            Get
                Return ResourceManager.GetString("Reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 If true, then reboot after shutdown. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RebootDescription() As String
            Get
                Return ResourceManager.GetString("RebootDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show Splash Screen 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShowSplash() As String
            Get
                Return ResourceManager.GetString("ShowSplash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Default Message 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Shutdown() As String
            Get
                Return ResourceManager.GetString("Shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The default shutdown message. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownDescription() As String
            Get
                Return ResourceManager.GetString("ShutdownDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Number of threads 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Threads() As String
            Get
                Return ResourceManager.GetString("Threads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 UDP Port 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property UDPPort() As String
            Get
                Return ResourceManager.GetString("UDPPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enter the UDP Port number for the broadcast messages. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property UDPPortDescription() As String
            Get
                Return ResourceManager.GetString("UDPPortDescription", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
