'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WakeOnLan.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Abort {0} Error: {1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AbortFailed() As String
            Get
                Return ResourceManager.GetString("AbortFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Aborting... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Aborting() As String
            Get
                Return ResourceManager.GetString("Aborting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Aborting shutdown command on {0} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AbortingShutdown() As String
            Get
                Return ResourceManager.GetString("AbortingShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Abort Shutdown in progress... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AbortShutdown() As String
            Get
                Return ResourceManager.GetString("AbortShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Abort {0} successful 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AbortSuccess() As String
            Get
                Return ResourceManager.GetString("AbortSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 WakeOnLAN is still running in the task tray. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ackMinimized() As String
            Get
                Return ResourceManager.GetString("ackMinimized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Send an email 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_email() As String
            Get
                Return ResourceManager.GetString("actions_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Hibernate computer 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_hibernate() As String
            Get
                Return ResourceManager.GetString("actions_hibernate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Hibernate All Computers 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_hibernateAll() As String
            Get
                Return ResourceManager.GetString("actions_hibernateAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Popup a message 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_popup() As String
            Get
                Return ResourceManager.GetString("actions_popup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown computer 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_shutdown() As String
            Get
                Return ResourceManager.GetString("actions_shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown All Computers 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_shutdownAll() As String
            Get
                Return ResourceManager.GetString("actions_shutdownAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown Group 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_shutdownGroup() As String
            Get
                Return ResourceManager.GetString("actions_shutdownGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sleep computer 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_sleep() As String
            Get
                Return ResourceManager.GetString("actions_sleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sleep All Computers 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_sleepAll() As String
            Get
                Return ResourceManager.GetString("actions_sleepAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start computer 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_start() As String
            Get
                Return ResourceManager.GetString("actions_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start All computers 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_startAll() As String
            Get
                Return ResourceManager.GetString("actions_startAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start Group 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property actions_startGroup() As String
            Get
                Return ResourceManager.GetString("actions_startGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 All machines 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AllMachines() As String
            Get
                Return ResourceManager.GetString("AllMachines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AreYouSure() As String
            Get
                Return ResourceManager.GetString("AreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Begin shutdown... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property BeginShutdown() As String
            Get
                Return ResourceManager.GetString("BeginShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Your changes will be lost. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ChangesLost() As String
            Get
                Return ResourceManager.GetString("ChangesLost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Changes have not been saved 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ChangesNotSaved() As String
            Get
                Return ResourceManager.GetString("ChangesNotSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copyright (c) 2004 - 2018, Aquila Technology 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Copyright() As String
            Get
                Return ResourceManager.GetString("Copyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Emergency shutdown! 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DefaultEmergency() As String
            Get
                Return ResourceManager.GetString("DefaultEmergency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 System is shutting down! 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DefaultMessage() As String
            Get
                Return ResourceManager.GetString("DefaultMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Delete {0} records? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Done 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Done() As String
            Get
                Return ResourceManager.GetString("Done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Emergency shutdown started 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property EmergencyShutdown() As String
            Get
                Return ResourceManager.GetString("EmergencyShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Must be greater than 1. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property errGreaterThan1() As String
            Get
                Return ResourceManager.GetString("errGreaterThan1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error: {0} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ErrorMsg() As String
            Get
                Return ResourceManager.GetString("ErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Wake on LAN has detected that your user settings file has become corrupted. This may be due to a crash or improper exiting of the program. Wake on LAN must reset your user settings in order to continue.\n\nClick Yes to reset your user settings and continue.\n\nClick No if you wish to attempt manual repair or to rescue information before proceeding. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property errUserConfigCorrupt() As String
            Get
                Return ResourceManager.GetString("errUserConfigCorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Corrupt user settings 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property errUserConfigTitle() As String
            Get
                Return ResourceManager.GetString("errUserConfigTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You must set a proper UserID and Password for a scheduled task. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property errUserID() As String
            Get
                Return ResourceManager.GetString("errUserID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Must be greater than 1 and less than 52. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property errWeeks() As String
            Get
                Return ResourceManager.GetString("errWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Settings were exported to [{0}] 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExportedTo() As String
            Get
                Return ResourceManager.GetString("ExportedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Host {0} not responding 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property HostNotResponding() As String
            Get
                Return ResourceManager.GetString("HostNotResponding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This will IMMEDIATELY reboot THIS machine.  Are you sure? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ImmediateReboot() As String
            Get
                Return ResourceManager.GetString("ImmediateReboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This will IMMEDIATELY shutdown THIS machine.  Are you sure? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ImmediateShutdown() As String
            Get
                Return ResourceManager.GetString("ImmediateShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Settings were imported from [{0}] 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ImportedFrom() As String
            Get
                Return ResourceManager.GetString("ImportedFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IPv4 interface information for {0}.{1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property interfaceInfo() As String
            Get
                Return ResourceManager.GetString("interfaceInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 New 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property isNew() As String
            Get
                Return ResourceManager.GetString("isNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 At {0} on {1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_at() As String
            Get
                Return ResourceManager.GetString("lit_at", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 At {0} every {1} day(s) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_atDays() As String
            Get
                Return ResourceManager.GetString("lit_atDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 At {0} every {1} every {2} weeks, starting {3} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_atWeeks() As String
            Get
                Return ResourceManager.GetString("lit_atWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Delete {0} record(s) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_DeleteRecords() As String
            Get
                Return ResourceManager.GetString("lit_DeleteRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disabled 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Disabled() As String
            Get
                Return ResourceManager.GetString("lit_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enabled 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Enabled() As String
            Get
                Return ResourceManager.GetString("lit_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Error() As String
            Get
                Return ResourceManager.GetString("lit_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 False 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_false() As String
            Get
                Return ResourceManager.GetString("lit_false", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid command line 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Invalid() As String
            Get
                Return ResourceManager.GetString("lit_Invalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Multiple triggers defined 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_multipleTriggers() As String
            Get
                Return ResourceManager.GetString("lit_multipleTriggers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Never 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Never() As String
            Get
                Return ResourceManager.GetString("lit_Never", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 None 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_None() As String
            Get
                Return ResourceManager.GetString("lit_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} does not appear to have read access rights to the WOL Scheduler database. Grant access? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_noRights() As String
            Get
                Return ResourceManager.GetString("lit_noRights", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Machine not found 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_notFound() As String
            Get
                Return ResourceManager.GetString("lit_notFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Queued 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Queued() As String
            Get
                Return ResourceManager.GetString("lit_Queued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ready 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Ready() As String
            Get
                Return ResourceManager.GetString("lit_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remove IP Address from {0} record(s) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_RemoveIP() As String
            Get
                Return ResourceManager.GetString("lit_RemoveIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Running 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Running() As String
            Get
                Return ResourceManager.GetString("lit_Running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 True 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_true() As String
            Get
                Return ResourceManager.GetString("lit_true", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unknown 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property lit_Unknown() As String
            Get
                Return ResourceManager.GetString("lit_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Host is OFFLINE 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property OffLine() As String
            Get
                Return ResourceManager.GetString("OffLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Host is ONLINE 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property OnLine() As String
            Get
                Return ResourceManager.GetString("OnLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Broadcast Address 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Opt_BroadcastAddress() As String
            Get
                Return ResourceManager.GetString("Opt_BroadcastAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enter the broadcast IP Address for the WOL broadcast packets. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Opt_BroadcastDesc() As String
            Get
                Return ResourceManager.GetString("Opt_BroadcastDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pausing... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Pausing() As String
            Get
                Return ResourceManager.GetString("Pausing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Polling {0} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Polling() As String
            Get
                Return ResourceManager.GetString("Polling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Properties - {0} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Properties() As String
            Get
                Return ResourceManager.GetString("Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RDP files (*.rdp)|*.rdp|All files (*.*)|*.* 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property rdp_filter() As String
            Get
                Return ResourceManager.GetString("rdp_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Browse RDP Files 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property rdp_title() As String
            Get
                Return ResourceManager.GetString("rdp_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} Response Time {1} ms 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ResponseTime() As String
            Get
                Return ResourceManager.GetString("ResponseTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select a WakeOnLan settings file to import 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SelectFile() As String
            Get
                Return ResourceManager.GetString("SelectFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sending shutdown command to {0} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SendShutdown() As String
            Get
                Return ResourceManager.GetString("SendShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sent Wake Up packet to {0} at {1}... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SentTo() As String
            Get
                Return ResourceManager.GetString("SentTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown failed for {0} {1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownFailed() As String
            Get
                Return ResourceManager.GetString("ShutdownFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutting down in {0} seconds... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShutDownSeconds() As String
            Get
                Return ResourceManager.GetString("ShutDownSeconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutdown {0} successful 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownSuccessful() As String
            Get
                Return ResourceManager.GetString("ShutdownSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shutting down... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ShuttingDown() As String
            Get
                Return ResourceManager.GetString("ShuttingDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skipping... 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Skipping() As String
            Get
                Return ResourceManager.GetString("Skipping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Successful 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Successful() As String
            Get
                Return ResourceManager.GetString("Successful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Wake on LAN 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Daily 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property triggerDaily() As String
            Get
                Return ResourceManager.GetString("triggerDaily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Monthly 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property triggerMonthly() As String
            Get
                Return ResourceManager.GetString("triggerMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 One Time 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property triggerOneTime() As String
            Get
                Return ResourceManager.GetString("triggerOneTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Weekly 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property triggerWeekly() As String
            Get
                Return ResourceManager.GetString("triggerWeekly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 -- use default -- 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property useDefault() As String
            Get
                Return ResourceManager.GetString("useDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Version {0}.{1:00}.{2} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Where do you want to save the settings? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property WhereSave() As String
            Get
                Return ResourceManager.GetString("WhereSave", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
